version: '1.0.{build}'

notifications:
  - provider: Email
    to:
      - scrgiorgio@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true  
   
environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019  
  Qt5_DIR: C:\\Qt\\5.9\\msvc2017_64\\lib\\cmake\\Qt5
  MINICONDA: C:\\Miniconda36-x64
  matrix:
    - PYTHON_VERSION: 3.6    
      Python_EXECUTABLE: C:\\Python36-x64\\python.exe
      PYTHON_TAG: cp36
    - PYTHON_VERSION: 3.7
      Python_EXECUTABLE: C:\\Python37-x64\\python.exe
      PYTHON_TAG: cp37
    - PYTHON_VERSION: 3.8
      Python_EXECUTABLE: C:\\Python38-x64\\python.exe
      PYTHON_TAG: cp38
 
build_script:
  - cd %APPVEYOR_BUILD_FOLDER% 
  - CALL scripts/build_win.bat

test: off

