version: '1.0.{build}'

notifications:
  - provider: Email
    to:
      - scrgiorgio@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true  
   
environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019  
  matrix:
    - PYTHON_VERSION: 38
    - PYTHON_VERSION: 37
    - PYTHON_VERSION: 36    
 
build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER% 
  - cmd: .\scripts\build_win.bat 

test: off

