version: '1.0.{build}'

notifications:
  - provider: Email
    to:
      - scrgiorgio@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true  
   
environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  PYPI_USERNAME: scrgiorgio
  PYPI_PASSWORD:
    secure: 6DHH80JPNRCtIYxWc/h88Q==   
  matrix:
    - PYTHON_VERSION: 38
      BUILD_CONDA: 0
    - PYTHON_VERSION: 37
    - PYTHON_VERSION: 36    
 
build_script:
  - cmd: choco install -y --allow-empty-checksums swig 
  - cmd: cd %APPVEYOR_BUILD_FOLDER% 
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: .\scripts\build.bat 

test: off


