version: '1.0.{build}'

notifications:
  - provider: Email
    to:
      - scrgiorgio@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true  
   
environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019  
  Qt5_DIR: C:\\Qt\\5.9\\msvc2017_64\\lib\\cmake\\Qt5  
  MINICONDA_DIR: C:\\Miniconda36-x64
  matrix:
    - PYTHON_VERSION: 36    
      Python_EXECUTABLE=C:\Python36-x64\python.exe
    - PYTHON_VERSION: 37
      Python_EXECUTABLE=C:\Python37-x64\python.exe
    - PYTHON_VERSION: 38
      Python_EXECUTABLE=C:\Python38-x64\python.exe
 
build_script:
  - cmd: SETLOCAL EnableDelayedExpansion
  - cmd: choco install -y --allow-empty-checksums swig
  - cmd: cd %APPVEYOR_BUILD_FOLDER% 
  - cmd: set GIT_TAG=false
  - cmd: git describe --tags --exact-match 2>NUL
  - cmd: if ERRORLEVEL == 0 (set GIT_TAG=true)
  - cmd: .\scripts\build_win.bat
  - cmd: if "%PYTHON_VERSION%" == "38" appveyor exit
  - cmd: cd Release\OpenVisus
  - cmd: .\scripts\build_conda.bat
  
test: off

