version: '1.0.{build}'

# important the commit message
# [full_matrix]
# [deploy_pypi]   IMPORTANT: for deploy_pypi remember to change the version in CMake/setup.py
# [deploy_github]

notifications:
  - provider: Email
    to:
      - scrgiorgio@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true  
  
environment:
  QT5_DIR: C:/Qt/5.10.1/msvc2017_64
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  CMAKE_GENERATOR: Visual Studio 15 2017 Win64
  PYPI_USERNAME: scrgiorgio
  PYPI_PASSWORD:
    secure: 6DHH80JPNRCtIYxWc/h88Q==   
  matrix:
    - PYTHON_EXECUTABLE: C:/Python37-x64/python.exe 
      ONLY_FULL_MATRIX: false  
    - PYTHON_EXECUTABLE: C:/Python36-x64/python.exe
      ONLY_FULL_MATRIX: true
  
# enable cache for vcpkg
cache: c:\tools\vcpkg\installed\  
  
# 
#if you need to debug uncomment these lines (see https://www.appveyor.com/docs/how-to/rdp-to-build-worker/)
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


init:
  - ps: | 
      If (($env:ONLY_FULL_MATRIX -eq "true") -and !($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[full_matrix]"))) {
        Write-Host "Skipping build, since ONLY_FULL_MATRIX=true and commit message does not contain [full_matrix]"
        Exit-AppveyorBuild
      }

install:
  - choco install -y --allow-empty-checksums swig 

build_script:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: cd c:\tools\vcpkg
  - cmd: vcpkg.exe install zlib:x64-windows lz4:x64-windows tinyxml:x64-windows freeimage:x64-windows openssl:x64-windows curl:x64-windows
  - cmd: cd %APPVEYOR_BUILD_FOLDER%  
  - cmd: IF 1==1 "%PYTHON_EXECUTABLE%" -m pip install --user numpy
  - cmd: mkdir build 
  - cmd: cd build 
  - cmd: cmake -G "%CMAKE_GENERATOR%" -DCMAKE_TOOLCHAIN_FILE="c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="x64-windows" -DQt5_DIR="%QT5_DIR%/lib/cmake/Qt5" -DPYPI_USERNAME=%PYPI_USERNAME% -DPYPI_PASSWORD=%PYPI_PASSWORD% -DPYTHON_EXECUTABLE=%PYTHON_EXECUTABLE% ../
  - cmd: cmake --build . --target ALL_BUILD --config RelWithDebInfo
  - cmd: cmake --build . --target RUN_TESTS --config RelWithDebInfo
  - cmd: cmake --build . --target INSTALL       --config RelWithDebInfo
  - cmd: cmake --build . --target deploy        --config RelWithDebInfo
  - ps: | 
        If ( $env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[deploy_github]") ) {
           cmake --build . --target sdist --config RelWithDebInfo
           IF 1==1 "%PYTHON_EXECUTABLE%" -c "import os;import glob;f=glob.glob('install/dist/*.zip')[0];os.rename(f,f.replace('.zip','.win_amd64.zip'))"
        }
  - ps: | 
        If ( $env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[deploy_pypi]" )) {
            cmake --build . --target bdist_wheel   --config RelWithDebInfo
            cmake --build . --target pypi          --config RelWithDebInfo
        }
   
# test are already in cmake
test: off

after_build:
  - ps: | 
      if ( -not (Test-Path "%APPVEYOR_BUILD_FOLDER%\build\install\dist\*.zip")) {
        Exit-AppveyorBuild
      }    

artifacts:
    - path: "%APPVEYOR_BUILD_FOLDER%\build\install\dist\*.zip"
      name: UploadToGitReleases
 
deploy:
  - provider: GitHub
    auth_token:
      secure: nwK8bGTRUynj+58b7E8Rgur5/0YvfIivBflFb5AaUrpC5BSTpcLbA4Ac+cCF6L4/
    artifact: UploadToGitReleases


