version: '1.0.{build}'

notifications:
  - provider: Email
    to:
      - scrgiorgio@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true  
   
environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019  
  matrix:
    - PYTHON_VERSION: 36    
    - PYTHON_VERSION: 37
    - PYTHON_VERSION: 38
 
build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER% 
  - cmd: SETLOCAL EnableDelayedExpansion
  - cmd: set Python_EXECUTABLE=C:\Python%PYTHON_VERSION%-x64\python.exe
  - cmd: set Qt5_DIR=C:\Qt\5.9\msvc2017_64\lib\cmake\Qt5  
  - cmd: set MINICONDA_DIR=C:\Miniconda36-x64
  - cmd: set GIT_TAG="false"
  - cmd: git describe --tags --exact-match >tmp.txt 2>NUL
  - cmd: if ERRORLEVEL == 0 ( set GIT_TAG="true" )
  - cmd: if "%GIT_TAG%" == "true" ( echo "QUI" )
  - cmd: choco install -y --allow-empty-checksums swig
  - cmd: .\scripts\build_win.bat
  - cmd: if "%PYTHON_VERSION%" == "38" appveyor exit
  - cmd: cd Release\OpenVisus
  - cmd: .\scripts\build_conda.bat
  
test: off

