version: '1.0.{build}'

notifications:
  - provider: Email
    to:
      - scrgiorgio@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true  
   
environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019  
  Qt5_DIR: C:\\Qt\\5.9\\msvc2017_64\\lib\\cmake\\Qt5
  matrix:
    - PYTHON_VERSION: 38
      Python_EXECUTABLE: C:\\Python38-x64\\python.exe
    - PYTHON_VERSION: 37
      Python_EXECUTABLE: C:\\Python37-x64\\python.exe
      CONDA_DIR: C:\\Miniconda37-x64
    - PYTHON_VERSION: 36    
      Python_EXECUTABLE: C:\\Python36-x64\\python.exe
      CONDA_DIR: C:\\Miniconda36-x64
 
build_script:
  - cd %APPVEYOR_BUILD_FOLDER% 
  - .\scripts\build_win.bat 
  - if NOT "%CONDA_DIR%" == "" ( .\scripts\build_conda.bat )

test: off

