version: '1.0.{build}'

notifications:
  - provider: Email
    to:
      - scrgiorgio@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true  
  
environment:

  QT5_DIR: C:/Qt/5.10.1/msvc2017_64/lib/cmake/Qt5
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  CMAKE_GENERATOR: Visual Studio 15 2017 Win64
  PYPI_USERNAME: scrgiorgio
  PYPI_PASSWORD:
    secure: 6DHH80JPNRCtIYxWc/h88Q==    
  matrix:
    - PYTHON_VERSION: 3.6
      PYTHONHOME: win32/python36  
      SKIP_NOTAG: false
    - PYTHON_VERSION: 3.7
    	PYTHONHOME: win32/python37
      SKIP_NOTAG: false
  
# 
#if you need to debug uncomment these lines (see https://www.appveyor.com/docs/how-to/rdp-to-build-worker/)
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


# use SKIP_NOTAG to skip building if tag is not present
init:
  - ps: | 
      If (($env:SKIP_NOTAG -eq "true") -and ($env:APPVEYOR_REPO_TAG -ne "true")) {
          Write-Host "Skipping build, not at a tag."
          Exit-AppveyorBuild
      }

install:
  - choco install -y --allow-empty-checksums swig 

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%  
  - git submodule update --init %PYTHONHOME%
  - %PYTHONHOME%\python.exe -m pip install --user --upgrade numpy setuptools wheel twine
  - mkdir build 
  - cd build 
  - cmake -G "%CMAKE_GENERATOR%" -DQt5_DIR="%QT5_DIR%" -DPYPI_USERNAME=%PYPI_USERNAME% -DPYPI_PASSWORD=%PYPI_PASSWORD% -DPYTHONHOME=%PYTHONHOME% ../ 
  - cmake --build . --target ALL_BUILD --config RelWithDebInfo
  - cmake --build . --target RUN_TESTS --config RelWithDebInfo
  - ps: >-
      If ($env:APPVEYOR_REPO_TAG -eq "true") { 
         Invoke-Expression "cmake --build . --target INSTALL --config RelWithDebInfo" 
         Invoke-Expression "cmake --build . --target deploy  --config RelWithDebInfo" 
         Invoke-Expression "cmake --build . --target dist    --config RelWithDebInfo" 
         Invoke-Expression "cmake --build . --target pypi    --config RelWithDebInfo" 
      } 
   
# test are already in cmake
test: off

artifacts:
    - path: .\build\install\dist\*.zip
      name: UploadToGitReleases
 
deploy:
  - provider: GitHub
    auth_token:
      secure: nwK8bGTRUynj+58b7E8Rgur5/0YvfIivBflFb5AaUrpC5BSTpcLbA4Ac+cCF6L4/
    artifact: UploadToGitReleases
    on:
      appveyor_repo_tag: true 


