version: '1.0.{build}'

notifications:
  - provider: Email
    to:
      - scrgiorgio@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true  
   
environment:
  CMAKE_BUILD_TYPE: Release
  QT5_DIR: C:/Qt/5.11/msvc2017_64/lib/cmake/Qt5
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  CMAKE_GENERATOR: Visual Studio 15 2017 Win64
  PYPI_USERNAME: scrgiorgio
  PYPI_PASSWORD:
    secure: 6DHH80JPNRCtIYxWc/h88Q==   
  matrix:
    - PYTHON_EXECUTABLE: C:/Python38-x64/python.exe 
      DEFAULT_ENABLED: true  
      PYTHON_TAG: cp38
    - PYTHON_EXECUTABLE: C:/Python37-x64/python.exe 
      DEFAULT_ENABLED: true  
      PYTHON_TAG: cp37
    - PYTHON_EXECUTABLE: C:/Python36-x64/python.exe 
      DEFAULT_ENABLED: true 
      PYTHON_TAG: cp36    
 
init:
  - ps: | 
      If ($env:APPVEYOR_REPO_TAG -eq "false" -and $env:DEFAULT_ENABLED -eq "false") {
        Write-Host "Skipping build"
        Exit-AppveyorBuild
      }   

build_script:
  - cmd: choco install -y --allow-empty-checksums swig 
  - cmd: cd %APPVEYOR_BUILD_FOLDER% 
  - cmd: .\scripts\build.bat 

test: off


