version: '1.0.{build}'

os: Visual Studio 2017

platform:
  - x64
  
notifications:
  - provider: Email
    to:
      - scrgiorgio@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true  
  
environment:
  CONFIGURATION: RelWithDebInfo
  GENERATOR: Visual Studio 15 2017 Win64
  QT5_DIR: C:/Qt/5.10.1/msvc2017_64/lib/cmake/Qt5
  
matrix:
  - PYTHON_DIR: "C:\\Python27-x64"
  - PYTHON_DIR: "C:\\Python36-x64" 
  - PYTHON_DIR: "C:\\Python37-x64" 


#if you need to debug uncomment these lines (see https://www.appveyor.com/docs/how-to/rdp-to-build-worker/)
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - choco install -y --allow-empty-checksums swig 

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build 
  - cd build 
  - set PATH=%PYTHON_DIR%;%PYTHON_DIR%\Scripts;%PATH%
  - python -m pip install numpy setuptools wheel twine
  - cmake -G "%GENERATOR%" -DQt5_DIR="%QT5_DIR%" ..
  - cmake --build . --target ALL_BUILD --config %CONFIGURATION%
  - cmake --build . --target RUN_TESTS --config %CONFIGURATION% 
  - cmake --build . --target INSTALL   --config %CONFIGURATION% 

# test are already in cmake
test: off

artifacts:
    - path: .\build\install\dist\*.whl
      name: OpenVisusDeployToGitReleases
 
deploy:
  - provider: GitHub
    auth_token:
      secure: nwK8bGTRUynj+58b7E8Rgur5/0YvfIivBflFb5AaUrpC5BSTpcLbA4Ac+cCF6L4/
    artifact: OpenVisusDeployToGitReleases
    on:
      appveyor_repo_tag: true 
