language: cpp

sudo: required

git:
  submodules: false

services:
  - docker

notifications:
  email:
    recipients:
      - scrgiorgio@gmail.com
    on_success: always
    on_failure: always 

matrix:
  fast_finish: true
  include:

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: ['PYTHON_VERSION=3.8'] 

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: ['PYTHON_VERSION=3.7']
    
    - os: osx
      osx_image: xcode9.4 
      compiler: clang
      env: ['PYTHON_VERSION=3.6']

script:
    - >
      cd "${TRAVIS_BUILD_DIR}" 
      export GIT_TAG=${TRAVIS_TAG}
      bash scripts/build_osx.sh
      cd build_osx/Release/OpenVisus 
      bash scripts/build_conda.sh 
    

