language: cpp

sudo: required

cache:
   directories:
     - ~/.cached/OpenVisus

services:
  - docker

notifications:
  email:
    recipients:
      - scrgiorgio@gmail.com
    on_success: always
    on_failure: always 
    
env:
  global:
    - PYPI_USERNAME=scrgiorgio
    - secure: EAZwSiQCFdTjcKDmHLFpWgX7WnGKwTtptkTvXYLcMPSUMxGymTCOTI1h8jjhxGig3k4Jni1X1gx9c8+LkcMd/yjbzDiOnIjCAVRc1hmCijAgu9j3G1ZMll4E38T7Iq6jE3/DZyb7pfK3X4NQopF/5uySIGeoH25CHwcNyr36k8Ba+qYtanPwTG1D+EVIago8qqL5yG5rslAf7Y69+zVbNa/JAUhow4fw0RAwVp+kgMC7Fj7iSMuN4NmS176VZEjD593zbiBgW+veEN0Z2MLD4vG7nq+w5u5JJYuz+Q4EiB5CCek5hhj17fJMWuAA23RZAlq4X/2oS5bKg/etHK5iVeM8ODKBX2bBHOxQoqwOaOVf0sEs5ranwVLR/77FrhFEECKAmkfFHwGGViWTvdE+F/7XqjLQK9Zm2f+T+rMHxrm1RknbXz271TNahqCHnMsmpaz98WbBHjdp2aQfU+nV/l6XLJnAf0R58ISiVdnDOy3BgQsiWIyxjZc6gRSwLg6EzAS2XlgQOmXhDo8lYoaepuK4OWvdIf+bqw0Y3b0uvrpHlAEpIG0tzzZw6ldq3CdvKD+46Vz+ZtEQBi0GBPy1Env1RHILzlkUwn6LSjVnKYY/TZxIi4ha73yo2BwJ1Q6hpdjVFgHJkEY3a72UCnOBIVnaalGv9lu/EjaixrnU6Nc=  

conditions: v1 
  
matrix:
  fast_finish: true
  include:
  
    # ///////////////////////////////// manylinux (i.e. centos)
    
    - os: linux
      dist: trusty
      env: ['PYTHON_VERSION=3.6.6','DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64']       
      addons: 
        apt:
          packages: ['g++-4.9']
          sources: ['ubuntu-toolchain-r-test']     
          
    - os: linux
      dist: trusty
      if: tag IS present OR commit_message =~ /\[full_matrix\]/
      env: ['PYTHON_VERSION=3.5.1','DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64']       
      addons: 
        apt:
          packages: ['g++-4.9']
          sources: ['ubuntu-toolchain-r-test']               

    - os: linux
      dist: trusty
      if: tag IS present OR commit_message =~ /\[full_matrix\]/
      env: ['PYTHON_VERSION=3.4.1','DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64']       
      addons: 
        apt:
          packages: ['g++-4.9']
          sources: ['ubuntu-toolchain-r-test']       

    - os: linux
      dist: trusty
      if: tag IS present OR commit_message =~ /\[full_matrix\]/
      env: ['PYTHON_VERSION=2.7','DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64']       
      addons: 
        apt:
          packages: ['g++-4.9']
          sources: ['ubuntu-toolchain-r-test']   

    # ///////////////////////////////// osx 10.13
    
    - os: osx
      osx_image: xcode9.4 
      compiler: clang
      env: [PYTHON_VERSION=3.6.5]   
      
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      if: tag IS present OR commit_message =~ /\[full_matrix\]/  
      env: [PYTHON_VERSION=3.7.1]                
      
    - os: osx
      osx_image: xcode9.4 
      compiler: clang
      if: tag IS present OR commit_message =~ /\[full_matrix\]/  
      env: [PYTHON_VERSION=3.5.1]                          
          
    - os: osx
      osx_image: xcode9.4 
      compiler: clang
      if: tag IS present OR commit_message =~ /\[full_matrix\]/  
      env: [PYTHON_VERSION=2.7.15] 
      
    # ///////////////////////////////// osx 10.12
      
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      if: tag IS present OR commit_message =~ /\[full_matrix\]/
      env: ['PYTHON_VERSION=3.6.1']      
      
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      if: tag IS present OR commit_message =~ /\[full_matrix\]/
      env: ['PYTHON_VERSION=3.7.1']           
         
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      if: tag IS present OR commit_message =~ /\[full_matrix\]/
      env: ['PYTHON_VERSION=3.5.1']              
            
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      if: tag IS present OR commit_message =~ /\[full_matrix\]/
      env: ['PYTHON_VERSION=2.7.14']   

    # ///////////////////////////////// trusty (Ubuntu 14.04)
       
    - os: linux
      dist: trusty
      env: ['PYTHON_VERSION=3.6']       
      addons: 
        apt:
          packages: ['g++-4.9']
          sources: ['ubuntu-toolchain-r-test']          
    
    - os: linux
      dist: trusty
      if: tag IS present OR commit_message =~ /\[full_matrix\]/
      env: ['PYTHON_VERSION=3.5.1']       
      addons: 
        apt:
          packages: ['g++-4.9']
          sources: ['ubuntu-toolchain-r-test']       
            
    - os: linux
      dist: trusty
      if: tag IS present OR commit_message =~ /\[full_matrix\]/
      env: ['PYTHON_VERSION=2.7']
      addons: 
        apt:
          packages: ['g++-4.9']
          sources: ['ubuntu-toolchain-r-test']    
          
          

    # ///////////////////////////////// trusty (Ubuntu 16)
       
    - os: linux
      dist: xenial
      env: ['PYTHON_VERSION=3.6']       
      addons: 
        apt:
          packages: ['g++-4.9']
          sources: ['ubuntu-toolchain-r-test']          
    
    - os: linux
      dist: xenial
      if: tag IS present OR commit_message =~ /\[full_matrix\]/
      env: ['PYTHON_VERSION=3.5.1']       
      addons: 
        apt:
          packages: ['g++-4.9']
          sources: ['ubuntu-toolchain-r-test']       
            
    - os: linux
      dist: xenial
      if: tag IS present OR commit_message =~ /\[full_matrix\]/
      env: ['PYTHON_VERSION=2.7']
      addons: 
        apt:
          packages: ['g++-4.9']
          sources: ['ubuntu-toolchain-r-test']               
             

    # ///////////////////////////////// opensuse

    - os: linux
      dist: trusty
      if: tag IS present OR commit_message =~ /\[full_matrix\]/
      env: ['PYTHON_VERSION=3.6.6','DOCKER_IMAGE=opensuse:leap']
      addons: 
        apt:
          packages: ['g++-4.9']
          sources: ['ubuntu-toolchain-r-test']    
          
    - os: linux
      dist: trusty
      if: tag IS present OR commit_message =~ /\[full_matrix\]/
      env: ['PYTHON_VERSION=3.5.1','DOCKER_IMAGE=opensuse:leap']
      addons: 
        apt:
          packages: ['g++-4.9']
          sources: ['ubuntu-toolchain-r-test']    
          
    - os: linux
      dist: trusty
      if: tag IS present OR commit_message =~ /\[full_matrix\]/
      env: ['PYTHON_VERSION=2.7','DOCKER_IMAGE=opensuse:leap']
      addons: 
        apt:
          packages: ['g++-4.9']
          sources: ['ubuntu-toolchain-r-test']                       
          

    # ///////////////////////////////// alpine (disabled)
    # - os: linux
    #   dist: trusty
    #   if: tag IS present OR commit_message =~ /\[full_matrix\]/
    #   env: ['PYTHON_VERSION=3.6','DOCKER_IMAGE=alpine:3.7','DOCKER_SHELL=/bin/sh']       
    #   addons: 
    #     apt:
    #       packages: ['g++-4.9']
    #       sources: ['ubuntu-toolchain-r-test']  
    # - os: linux
    #   dist: trusty
    #   if: tag IS present OR commit_message =~ /\[full_matrix\]/
    #   env: ['PYTHON_VERSION=3.5','DOCKER_IMAGE=alpine:3.7','DOCKER_SHELL=/bin/sh']       
    #   addons: 
    #     apt:
    #       packages: ['g++-4.9']
    #       sources: ['ubuntu-toolchain-r-test']                

script:
   - |
     set -ex 

     VISUS_INTERNAL_DEFAULT=${VISUS_INTERNAL_DEFAULT:-1}
     PRETTY_LOG=${PRETTY_LOG:-1}
     if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then COMPILER=clang++ ; fi
     if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then COMPILER=g++-4.9 ; fi
     
     export DEPLOY_GITHUB=0
     if [[ "${TRAVIS_TAG}" != "" || "${TRAVIS_COMMIT_MESSAGE}" == *"[deploy_github]"* ]]; then
        echo "Doing deploy to github..."
        export DEPLOY_GITHUB=1
     fi
     
     export DEPLOY_PYPI=0
     if [[ "${TRAVIS_TAG}" != "" || "${TRAVIS_COMMIT_MESSAGE}" == *"[deploy_pypi]"* ]]; then
        if [[ $(uname) == "Darwin" || "${DOCKER_IMAGE}" == "quay.io/pypa/manylinux1_x86_64" ]]; then
           echo "Doing deploy to pypi..."
           export DEPLOY_PYPI=1
        fi     
     fi

     cd "${TRAVIS_BUILD_DIR}"  

     if [ -n "${DOCKER_IMAGE}" ]; then

        DOCKER_SHELL=${DOCKER_SHELL:-/bin/bash}
        DOCKER_ENV=${DOCKER_ENV:-}
        BUILD_DIR=${BUILD_DIR:-build}

        if [ "${PYTHON_VERSION}"         != "" ] ; then DOCKER_ENV="${DOCKER_ENV} -e PYTHON_VERSION=${PYTHON_VERSION}" ; fi
        if [ "${VISUS_INTERNAL_DEFAULT}" != "" ] ; then DOCKER_ENV="${DOCKER_ENV} -e VISUS_INTERNAL_DEFAULT=${VISUS_INTERNAL_DEFAULT}" ; fi
        if [ "${BUILD_DIR}"              != "" ] ; then DOCKER_ENV="${DOCKER_ENV} -e BUILD_DIR=${BUILD_DIR}" ; fi

        sudo docker rm -f mydocker || true
        sudo docker run -d -ti --name mydocker -v $(pwd):/home/OpenVisus ${DOCKER_ENV} ${DOCKER_IMAGE} ${DOCKER_SHELL}
        sudo docker exec mydocker ${DOCKER_SHELL} -c "cd /home/OpenVisus && ./build.sh"

        sudo chown -R "$USER":"$USER" ${BUILD_DIR}
        sudo chmod -R u+rwx           ${BUILD_DIR}

     else
        ./build.sh
     fi
    
     echo [distutils]                                  > ~/.pypirc
     echo index-servers =  pypi                       >> ~/.pypirc
     echo [pypi]                                      >> ~/.pypirc
     echo username=${PYPI_USERNAME}                   >> ~/.pypirc
     echo password=${PYPI_PASSWORD}                   >> ~/.pypirc
     if [[ "${DEPLOY_PYPI}" == "1" ]] ; then python -m pip install --user --upgrade twine  ; fi
     if [[ "${DEPLOY_PYPI}" == "1" ]] ; then python -m twine upload --skip-existing "${TRAVIS_BUILD_DIR}/build/install/dist/*.whl" ; fi

before_deploy:
  - export SDIST_FILENAME=$(find ${TRAVIS_BUILD_DIR}/build/install/dist -iname "*.tar.gz")

deploy:
  provider: releases
  api_key:
    secure: vvs+N/XwsigYj6pZIR0Lksg+FnA2M7bCy4aHj7at1nPOtX3ZHHdkSgIyd06awkiWSNg++fM6GIi7ewU+ftX9rGxgRFG5eWIKQyuHHPvNSIIcJe1cY7440Y6Kb2p58BFeGQxLJl0y3XlCObPW7yMoY7h9i6kTL6w7k3NkdWkFpdDaNXXEaGnzeoaM6u+iBmgAWgX9Ozlu+ogjFpw5b7QPtKgi1Bey/IbIeVWExuFnXsTJe3MDobdFvgJ0tewErnWAey3V8IXQzVMqdOIAl+xtu3RMmsdNymDAZpof31wFNLCr7BMmIg/O2QW1tnvNXuFX9Gpry5CKb7i0oxthiLyNTkh2sZQcAJcBdWJlP4LiSCBoJ2HuAc5XSqss8aXt/hHAzL3ICPtd6wVPlHEMK1+/EsC4WcO5X0ngzmGnn8eceIBFJiqYhI+c85GqUWPrFw+REKUsAwthMK0tNErruWZR1uubYnlyQYHpSaPdKie6o0aWK8Xit+GN3jkcqRrhQDwX3WFLxw2N07eh/f3vCD4m7GwRJfi5LXDuoLp3Qg5w23gi4ewp71v9oTZNT4K3vVEYuwzCyglppjyszQDvBAwxgxnWtSZh2nGEtwtDL5dRiIXehqfaK7mRKQ8iZwpQkuyTD+rsl45nTuNjeKYC3BLHd+NZhJI8qmcD6oykt+oxzjg=
  file: 
    - $SDIST_FILENAME
  skip_cleanup: true
  on:
    repo: sci-visus/OpenVisus
    tags: true
    all_branches: true

