language: cpp

sudo: required

git:
  submodules: false

services:
  - docker

notifications:
  email:
    recipients:
      - scrgiorgio@gmail.com
    on_success: always
    on_failure: always 

matrix:
  fast_finish: true
  include:

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: ['PYTHON_VERSION=3.8', 'ENABLE_CONDA=0'] 

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: ['PYTHON_VERSION=3.7', 'ENABLE_CONDA=1']
    
    - os: osx
      osx_image: xcode9.4 
      compiler: clang
      env: ['PYTHON_VERSION=3.6', 'ENABLE_CONDA=1']

script:
  - cd "${TRAVIS_BUILD_DIR}" 
  - export GIT_TAG=${TRAVIS_TAG}
  - scripts/build_osx.sh
  - if (( ENABLE_CONDA == 1 )) ; then cd build_osx/Release/OpenVisus && scripts/build_conda.sh ; fi
    

