

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:
- job: Linux
  pool:
    vmImage: 'visus/travis-image'
  steps:
  - script: echo hello from Linux
  - bash: |
      export PYTHON_VERSION: 3.6
      export GIT_TAG=${CIRCLE_TAG} 
      bash ./scripts/build_linux.sh
      cd build_linux/Release/OpenVisus 
      bash ./scripts/build_conda.sh
      
- job: MacOsx
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - script: echo hello from macOS 10.15
  - bash: |
      export PYTHON_VERSION=3.6
      export GIT_TAG=${TRAVIS_TAG}
      bash ./scripts/build_osx.sh
      cd build_osx/Release/OpenVisus 
      bash ./scripts/build_conda.sh
      
      
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo hello from Windows
  - script: |          
         set Qt5_DIR=C:\\Qt\\5.9\\msvc2017_64\\lib\\cmake\\Qt5
         set MINICONDA=C:\\Miniconda36-x64
         set PYTHON_VERSION=3.6    
         set Python_EXECUTABLE=C:\\Python36-x64\\python.exe
         set PYTHON_TAG=cp36  
         CALL scripts/build_win.bat