version: '2'

services:
  my-app:
    image: nsdf/openvisus-panel:latest
    env_file:
      - ./.env
    volumes:
      - ./v1:/nsdf/v1 
      - ./v2:/nsdf/v2 
      - ./nsdf-cache:/${VISUS_CACHE_DIR} # change as needed
    ports:
      - ${PANEL_PORT}:${PANEL_PORT}
    working_dir: /nsdf
    command:    python3 -m bokeh serve --address='0.0.0.0' --port ${PANEL_PORT} --allow-websocket-origin='*' ./v2/run.py