version: '2'

services:
  my-app:
    image: nsdf/openvisus-panel:0.3
    env_file:
      - ./.env
    volumes:
      - ./run-v1.py:/nsdf/run-v1.py 
      - ./run-v2.bokeh.py:/nsdf/run-v2.bokeh.py 
      - ./run-v2.panel.py:/nsdf/run-v2.panel.py 
      - ./nsdf-cache:/${VISUS_CACHE_DIR} # change as needed
    ports:
      - ${PANEL_PORT}:${PANEL_PORT}
    # command:  python3 -m panel serve --address='0.0.0.0' --port=${PANEL_PORT} --allow-websocket-origin='*' /nsdf/run-v1.py
    command:    python3 -m bokeh serve --address='0.0.0.0' --port ${PANEL_PORT} --allow-websocket-origin='*' /nsdf/run-v2.bokeh.py