version: 2

jobs:


  # ///////////////////////////////// manylinux
  linux-3.8:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.8
          BUILD_CONDA: 0
    steps:
      - checkout
      - run: 
          name: Build OpenVisus
          command: PYPI_DEPLOY=${CIRCLE_TAG} CONDA_DEPLOY=${CIRCLE_TAG} ./scripts/build.sh
  
  linux-3.7:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.7
    steps:
      - checkout
      - run: 
          name: Build OpenVisus
          command: PYPI_DEPLOY=${CIRCLE_TAG} CONDA_DEPLOY=${CIRCLE_TAG} ./scripts/build.sh
            
  linux-3.6:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.6
    steps:
      - checkout
      - run: 
          name: Build OpenVisus
          command: PYPI_DEPLOY=${CIRCLE_TAG} CONDA_DEPLOY=${CIRCLE_TAG} ./scripts/build.sh

workflows:
  version: 2
  OpenVisusWorkflow:
    jobs:
      - linux-3.8    
      - linux-3.7
      - linux-3.6
