version: 2

jobs:

  # ///////////////////////////////// manylinux
  manylinux-3.8:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
        environment:
          PYTHON_VERSION: 3.8.1
          VISUS_GUI: 0
    steps:
      - checkout
      - run: 
          name: Build OpenVisus
          command: |
            ./scripts/build.sh
  
  manylinux-3.7:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
        environment:
          PYTHON_VERSION: 3.7.1
          VISUS_GUI: 0
    steps:
      - checkout
      - run: 
          name: Build OpenVisus
          command: |
            ./scripts/build.sh
            
  manylinux-3.6:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
        environment:
          PYTHON_VERSION: 3.6.1
          VISUS_GUI: 0
    steps:
      - checkout
      - run: 
          name: Build OpenVisus
          command: |
            ./scripts/build.sh            

workflows:
  version: 2
  OpenVisusWorkflow:
    jobs:
      - manylinux-3.7
      - manylinux-3.6
