version: 2


jobs:

  Linux36:
    docker:
      - image: visus/travis-image
    steps:
      - run: yum -y install openssh-clients git 
      - checkout
      - run: |
             export PYTHON_VERSION=3.6
             bash ./scripts/build_linux.sh
             cd build_linux/Release/OpenVisus && bash ./scripts/build_conda.sh

  Linux37:
    docker:
      - image: visus/travis-image
    steps:
      - run: yum -y install openssh-clients git 
      - checkout
      - run: |
             export PYTHON_VERSION=3.7
             bash ./scripts/build_linux.sh
             cd build_linux/Release/OpenVisus && bash ./scripts/build_conda.sh

  Linux38:
    docker:
      - image: visus/travis-image
        environment:
    steps:
      - run: yum -y install openssh-clients git 
      - checkout
      - run: |
             export PYTHON_VERSION=3.8
             bash ./scripts/build_linux.sh
             # cd build_linux/Release/OpenVisus  && bash ./scripts/build_conda.sh BROKEN


  MacOs36:
    macos: 
      xcode: 11.3.0 
    steps:
      - checkout
      - run: |      
             bash ./scripts/build_osx.sh
             cd build_linux/Release/OpenVisus && bash ./scripts/build_conda.sh

  MacOs37:
    macos: 
      xcode: 11.3.0 
    steps:
      - checkout
      - run: |
             bash ./scripts/build_osx.sh
             cd build_linux/Release/OpenVisus && bash ./scripts/build_conda.sh

  MacOs38:
    macos: 
      xcode: 11.3.0 
    steps:
      - checkout
      - run: |
             bash ./scripts/build_osx.sh
             # cd build_linux/Release/OpenVisus  && bash ./scripts/build_conda.sh BROKEN


workflows:
  version: 2
  OpenVisusWorkflow:
    jobs:
      - Linux38:
          filters:
            tags:
              only: /.*/      
      - Linux37:
          filters:
            tags:
              only: /.*/        
      - Linux36:
          filters:
            tags:
              only: /.*/  
      - MacOs36:
          filters:
            tags:
              only: /.*/      
      - MacOs37:
          filters:
            tags:
              only: /.*/        
      - MacOs38:
          filters:
            tags:
              only: /.*/  

