version: 2

jobs:

  # ///////////////////////////////// osx 10.13
  # disabled because we need to pay
  # osx-10.13-3.7:
  #  macos:
  #    xcode: "9.4"  
  #    environment:
  #      PYTHON_VERSION=3.7.1       
  #  steps:
  #    - checkout
  #    - run: 
  #        name: Build OpenVisus
  #        command: |
  #          ./build.sh
  #          
  #osx-10.13-3.6:
  #  macos:
  #    xcode: "9.4"  
  #    environment:
  #      PYTHON_VERSION=3.6.1       
  #  steps:
  #    - checkout
  #    - run: 
  #        name: Build OpenVisus
  #        command: |
  #          ./build.sh            
  
  # ///////////////////////////////// manylinux
  manylinux-3.7:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
        environment:
          PYTHON_VERSION: 3.7.1
          DISABLE_OPENMP: 1
          VISUS_GUI: 0
    steps:
      - checkout
      - run: 
          name: Build OpenVisus
          command: |
            ./build.sh
            
  manylinux-3.6:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
        environment:
          PYTHON_VERSION: 3.6.1
          DISABLE_OPENMP: 1
          VISUS_GUI: 0
    steps:
      - checkout
      - run: 
          name: Build OpenVisus
          command: |
            ./build.sh            

workflows:
  version: 2
  OpenVisusWorkflow:
    jobs:
      #- osx-10.13-3.7
      #- osx-10.13-3.6
      - manylinux-3.7
      - manylinux-3.6