version: 2


jobs:

  Linux36:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.6
    steps:
      - run: yum -y install openssh-clients git 
      - checkout
      - run: |
             export GIT_TAG=${CIRCLE_TAG} 
             bash ./scripts/build_linux.sh
             cd build_linux/Release/OpenVisus && bash ./scripts/build_conda.sh

  Linux37:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.7
    steps:
      - run: yum -y install openssh-clients git 
      - checkout
      - run: |
             export GIT_TAG=${CIRCLE_TAG} 
             bash ./scripts/build_linux.sh
             cd build_linux/Release/OpenVisus && bash ./scripts/build_conda.sh

  Linux38:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.8
    steps:
      - run: yum -y install openssh-clients git 
      - checkout
      - run: |
             export GIT_TAG=${CIRCLE_TAG} 
             bash ./scripts/build_linux.sh
             # cd build_linux/Release/OpenVisus  && bash ./scripts/build_conda.sh BROKEN


workflows:
  version: 2
  OpenVisusWorkflow:
    jobs:
      - Linux38:
          filters:
            tags:
              only: /.*/      
      - Linux37:
          filters:
            tags:
              only: /.*/        
      - Linux36:
          filters:
            tags:
              only: /.*/  


