version: 2

jobs:

  # ///////////////////////////////// manylinux
  linux-3.8:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.8
          PYTHON_EXECUTABLE=/usr/local/bin/python3.8
          BUILD_CONDA: 0
          Qt5_DIR=/opt/qt59 
    steps:
      - checkout
      - run: 
          name: Build OpenVisus
          command: ./scripts/build_travis.sh
  
  linux-3.7:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.7
          PYTHON_EXECUTABLE=/usr/local/bin/python3.7
          Qt5_DIR=/opt/qt59 
    steps:
      - checkout
      - run: 
          name: Build OpenVisus
          command: ./scripts/build_travis.sh
            
  linux-3.6:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
        environment:
          PYTHON_VERSION: 3.6
          PYTHON_EXECUTABLE=/usr/local/bin/python3.6
          Qt5_DIR=/opt/qt59 
    steps:
      - checkout
      - run: 
          name: Build OpenVisus
          command: ./scripts/build_travis.sh   

workflows:
  version: 2
  OpenVisusWorkflow:
    jobs:
      - linux-3.8    
      - linux-3.7
      - linux-3.6
