version: 2

jobs:


  # ///////////////////////////////// manylinux
  linux-3.8:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.8
    steps:
      - run: yum -y install openssh-clients git # workaround circleci's fallback git's "object not found" error w/ tag
      - checkout
      - run: GIT_TAG=${CIRCLE_TAG} scripts/build_linux.sh
  
  linux-3.7:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.7
    steps:
      - run: yum -y install openssh-clients git # workaround circleci's fallback git's "object not found" error w/ tag
      - checkout
      - run: GIT_TAG=${CIRCLE_TAG} scripts/build_linux.sh
      - run: GIT_TAG=${CIRCLE_TAG} scripts/build_conda.sh
            
  linux-3.6:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.6
    steps:
      - run: yum -y install openssh-clients git # workaround circleci's fallback git's "object not found" error w/ tag
      - checkout
      - run: GIT_TAG=${CIRCLE_TAG} scripts/build_linux.sh
      - run: GIT_TAG=${CIRCLE_TAG} scripts/build_conda.sh

workflows:
  version: 2
  OpenVisusWorkflow:
    jobs:
      - linux-3.8:
          filters:
            tags:
              only: /.*/      
      - linux-3.7:
          filters:
            tags:
              only: /.*/        
      - linux-3.6:
          filters:
            tags:
              only: /.*/  


