version: 2

commands:

  workaround:
    steps:
      - run: yum -y install openssh-clients git 

  compile_openvisus:
    steps:
      - run: |
             export GIT_TAG=${CIRCLE_TAG} 
             bash ./scripts/build_linux.sh
             cd build_linux/Release/OpenVisus 
             bash ./scripts/build_conda.sh

jobs:

  linux-3.8:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.8
    steps:
      - workaround
      - checkout
      - compile_openvisus
  
  linux-3.7:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.7
    steps:
      - workaround
      - checkout
      - compile_openvisus
            
  linux-3.6:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.6
    steps:
      - workaround
      - checkout
      - compile_openvisus

workflows:
  version: 2
  OpenVisusWorkflow:
    jobs:
      - linux-3.8:
          filters:
            tags:
              only: /.*/      
      - linux-3.7:
          filters:
            tags:
              only: /.*/        
      - linux-3.6:
          filters:
            tags:
              only: /.*/  


