version: 2.1

jobs:

  linux-3.8:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.8
    steps:
      - checkout
      - run: 
          name: Build OpenVisus
          command: scripts/build_circleci.sh
  
  linux-3.7:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.7
    steps:
      - checkout
      - run: 
          name: Build OpenVisus
          command: scripts/build_circleci.sh
            
  linux-3.6:
    docker:
      - image: visus/travis-image
        environment:
          PYTHON_VERSION: 3.6
    steps:
      - checkout
      - run: 
          name: Build OpenVisus
          command: scripts/build_circleci.sh

workflows:
  version: 2
  untagged-build:
    jobs:
      - linux-3.8   
          filters:
            tags:
              only: /.*/ 
      - linux-3.7
          filters:
            tags:
              only: /.*/
      - linux-3.6
          filters:
            tags:
              only: /.*/