name: BuildOpenVisus

on: [push]

jobs:
        
  # ///////////////////////////////////////////////////////////////
  BuildOpenVisusJob:
  
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 6
      matrix:
        python-version: [ '3.6']  
        
    steps:
    # ____________________________________________
    - name: Checkout
      uses: actions/checkout@v2
      
    # ____________________________________________
    - name: Compile OpenVisus 
      shell: bash
      if: matrix.os == 'ubuntu-latest'
      env: 
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
           docker run -d -it --name mydocker -v $(pwd):/root/OpenVisus -w /root/OpenVisus -e PYTHON_VERSION=${{ matrix.python-version }} -e PYPI_USERNAME -e PYPI_PASSWORD visus/travis-image /bin/bash 
           docker exec mydocker /bin/bash -c "./scripts/build_linux.sh"

    # ____________________________________________
    - name: Install Miniconda 
      uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: 'latest'    
        python-version: ${{ matrix.python-version }}
        
    # ____________________________________________
    - name: Build OpenVisus conda package
      if: matrix.python-version != '3.8' 
      env: 
         ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      shell: bash -l {0}
      run: | 
           set -e  # stop or error
           set -x  # very verbose   
                 
           PYTHON_VERSION=${{ matrix.python-version }}  
      
           conda activate
           conda config --set always_yes yes --set changeps1 no --set anaconda_upload no
           conda create -q -n tmp python=${PYTHON_VERSION} numpy
           conda activate tmp   
           conda install conda-build anaconda-client numpy     

           cd build/Release/OpenVisus
           
           # I get some random crashes in Linux, so I'm using more actions than a simple configure here..
           conda uninstall pyqt || true
           PYTHONPATH=../ python -m OpenVisus remove-qt5
           PYTHONPATH=../ python -m OpenVisus install-pyqt5
           PYTHONPATH=../ python -m OpenVisus link-pyqt5 || true # this crashes on linux (after the sys.exit(0), so I should be fine)
           PYTHONPATH=../ python -m OpenVisus generate-scripts pyqt5
           PYTHONPATH=../ python -m OpenVisus test
           PYTHONPATH=../ python -m OpenVisus convert      
           
           PYTHONPATH=../ python -m OpenVisus test
           PYTHONPATH=../ python -m OpenVisus convert
         
           # https://anaconda.org/ViSUS/settings/access
           GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
           if [[ "${GIT_TAG}" != "" && "${ANACONDA_TOKEN}" != "" ]] ; then
              rm -Rf $(find ~/Miniconda3 -iname "openvisus*.tar.bz2")   
              python setup.py -q bdist_conda 
              CONDA_FILENAME=$(find ~/Miniconda3 -iname "openvisus*.tar.bz2"  | head -n 1)  
              anaconda -t "${ANACONDA_TOKEN}" upload "${CONDA_FILENAME}"
           fi

