name: build-openvisus
on: [push]

env:
  PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:

  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false  
      matrix:
        type: [ "cpython" , "conda" ]
        python-version: [ '3.7', '3.8', '3.9' , '3.10' ]
    steps:
    - name: git clone OpenVisus
      uses: actions/checkout@v2
    - name: install cpython
      uses: actions/setup-python@v2
      if: ${{ matrix.type == 'cpython' }} 
      with:
        python-version: ${{ matrix.python-version }}
    - name: Compile (cpython)
      shell: bash
      run: |
           set -ex
           export PYTHON_VERSION=${{ matrix.python-version }}
           source ./scripts/${{ matrix.type }}.windows.sh
      

  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false  
      matrix:
        type: [ "cpython" , "conda" ]
        python-version: [ '3.7', '3.8', '3.9' , '3.10' ]
    steps:
    - name: git clone OpenVisus
      uses: actions/checkout@v2
    - name: install cpython
      uses: actions/setup-python@v2
      if: ${{ matrix.type == 'cpython' }} 
      with:
        python-version: ${{ matrix.python-version }}
    - name: Compile (cpython)
      shell: bash
      run: |
           set -ex
           export PYTHON_VERSION=${{ matrix.python-version }}
           source ./scripts/${{ matrix.type }}.macos.sh
            
      
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    steps:
    - name: git clone OpenVisus
      uses: actions/checkout@v2
    - name: Compile cpython
      shell: bash
      run: |
           set -ex
           export PYTHON_VERSION=${{ matrix.python-version }}
           export DOCKER_IMAGE=visus/portable-linux-binaries_x86_64:4.1
           source scripts/ubuntu.sh










