name: BuildOpenVisus

on: [push]

jobs:


  # ///////////////////////////////////////////////////////////////
  BuildOpenVisus:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.6', '3.7', '3.8' ] 
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
        conda: ["false", "true"]
        exclude:
           - python-version: 3.8
             os: windows-latest
             conda: true
           - python-version: 3.8
             os: macos-latest
             conda: true
           - python-version: 3.8
             os: ubuntu-latest
             conda: true
             
    steps:
    
    # ____________________________________________
    - name: Install CMake
      uses: lukka/get-cmake@latest
      
    # ____________________________________________
    - name: Install Swig for windows
      if: matrix.os == 'windows-latest'
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install -y --allow-empty-checksums --no-progress cmake swig
        
    # ____________________________________________  
    - name: Install Swig for macos
      if: matrix.os == 'macos-latest'
      run: brew install swig
           
    # ____________________________________________  
    - name: Install SDK 10.9 for macos 
      if: matrix.os == 'macos-latest'
      run: cd /opt && git clone https://github.com/phracker/MacOSX-SDKs.git 
        
    # ____________________________________________
    - name: Install CPython 
      if: matrix.conda == 'false'
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }} 
        architecture: 'x64'
        
    # ____________________________________________
    - name: Install Miniconda 
      if: matrix.conda == 'true'
      uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: 'latest'    
        python-version: ${{ matrix.python-version }}
        activate-environment: tmp
        auto-update-conda: true

    # ____________________________________________
    - name: Configure Miniconda and install pyqt
      if: matrix.conda == 'true'
      shell: bash -l {0}
      run: |
           conda config --set always_yes yes --set changeps1 no --set anaconda_upload no   1>/dev/null
           conda install pyqt                                                              1>/dev/null        

    # ____________________________________________
    - name: Install Qt for windows
      if: matrix.os == 'windows-latest' && matrix.conda == 'false'
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        arch: 'win64_msvc2017_64'
        install-deps: 'true'  
        dir: C:\
        
     # ____________________________________________
    - name: Install Qt for macos
      if: matrix.os == 'macos-latest' && matrix.conda == 'false'
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        target: 'desktop'
        install-deps: 'true'  
        dir: /opt

    # ____________________________________________
    - name: Install glu on ubuntu
      if: matrix.os == 'ubuntu-latest' && matrix.conda == 'false'
      shell: bash
      run: |
           sudo apt-get install libglu1-mesa-dev 1>/dev/null

    # ____________________________________________
    - name: git clone OpenVisus
      uses: actions/checkout@v2
      
    # ____________________________________________
    - name: git clone visuscpp  
      run: git clone https://${{ secrets.VISUS_SLAM_ACCESS_TOKEN }}@github.com/sci-visus/slamcpp.git Libs/slamcpp

    # ____________________________________________
    - name: git clone opsray for windows
      if: matrix.os == 'windows-latest'    
      run: git clone https://github.com/sci-visus/ospray_win.git ExternalLibs/ospray_win

    # ____________________________________________
    - name: Compile OpenVisus on windows
      if: matrix.os == 'windows-latest'    
      shell: bash -l {0}
      run: |
           if [[  "${{ matrix.conda }}" == "true" ]] ; then Qt5_Dir=${CONDA_PREFIX}/Library ; fi
           mkdir -p build
           cd build
           cmake -G "Visual Studio 16 2019" -A "x64" -DQt5_DIR="${Qt5_Dir}/lib/cmake/Qt5" -DPython_EXECUTABLE=$(which python) ../
           cmake --build . --target ALL_BUILD --config Release --parallel 4
           cmake --build . --target install   --config Release

    # ____________________________________________
    - name: Compile OpenVisus on macos
      if: matrix.os == 'macos-latest'
      shell: bash -l {0}
      run: |
           if [[  "${{ matrix.conda }}" == "true" ]] ; then Qt5_Dir=${CONDA_PREFIX} ; fi
           mkdir -p build
           cd build
           cmake -GXcode -DQt5_DIR="${Qt5_Dir}/lib/cmake/Qt5" -DCMAKE_OSX_SYSROOT="/opt/MacOSX-SDKs/MacOSX10.9.sdk" -DPython_EXECUTABLE=$(which python)  ../
           cmake --build ./ --target ALL_BUILD --config Release --parallel 4 
           cmake --build ./ --target install   --config Release 


    # ____________________________________________
    - name: Compile OpenVisus on ubuntu
      if: matrix.os == 'ubuntu-latest'
      shell: bash -l {0}
      run: |
           if [[  "${{ matrix.conda }}" == "false" ]] ; then Qt5_DIR=/opt/qt512 ; fi
           if [[  "${{ matrix.conda }}" == "true"  ]] ; then Qt5_DIR=/opt/qt59  ; fi
           docker run -e PYTHON_VERSION=${{ matrix.python-version }} -e Qt5_DIR=${Qt5_DIR} -v $PWD:$PWD  -w $PWD visus/portable-linux-binaries /bin/bash -c "./scripts/build_linux.sh"
           sudo chown -R root:root  build
           sudo chmod -R a+rwx      build
           

    # ____________________________________________
    - name: Test OpenVisus 
      shell: bash -l {0}
      run: |
           cd build/Release/OpenVisus
           export PYTHONPATH=../
           python  -m OpenVisus configure  || true  # segmentation fault problem on linux
           python  -m OpenVisus test
           python  -m OpenVisus test-gui || true

    # ____________________________________________
    - name: Distrib OpenVisus on pypi
      if: matrix.conda == 'false'
      shell: bash
      run: |
           GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
           if [[ "${GIT_TAG}" != "" ]] ; then
             cd build/Release/OpenVisus
             python -m pip install setuptools wheel twine --upgrade 1>/dev/null || true
             PYTHON_VERSION=${{ matrix.python-version }}
             if [[  "${{ matrix.os }}" == "windows-latest" ]] ; then PLATFORM_NAME=win_amd64            ; fi
             if [[  "${{ matrix.os }}" == "macos-latest"   ]] ; then PLATFORM_NAME=macosx_10_9_x86_64   ; fi
             if [[  "${{ matrix.os }}" == "ubuntu-latest"  ]] ; then PLATFORM_NAME=manylinux2010_x86_64 ; fi
             python setup.py -q bdist_wheel --python-tag=cp${PYTHON_VERSION:0:1}${PYTHON_VERSION:2:1} --plat-name=${PLATFORM_NAME}
             python -m twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing  "dist/*.whl" 
           fi               

    # ____________________________________________
    - name: Distrib OpenVisus on conda
      shell: bash -l {0}   
      run: |
           GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
           if [[ "${GIT_TAG}" != ""  ]] ; then
             cd build/Release/OpenVisus
             conda install anaconda-client 1>/dev/null || true
             rm -Rf $(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2")  || true
             python setup.py -q bdist_conda 1>/dev/null
             CONDA_FILENAME=$(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2"  | head -n 1) 
             anaconda --verbose --show-traceback  -t ${{ secrets.ANACONDA_TOKEN }}   upload "${CONDA_FILENAME}"
           fi








