name: OpenVisusGitHubActions

on: [push]

jobs:

  MacOs36:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: compile-openvisus
      run: |
        export PYTHON_VERSION=3.6
        bash ./scripts/build_osx.sh
        cd build_osx/Release/OpenVisus 
        bash ./scripts/build_conda.sh

  MacOs37:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: compile-openvisus
      run: |
        export PYTHON_VERSION=3.7
        bash ./scripts/build_osx.sh
        cd build_osx/Release/OpenVisus  
        bash ./scripts/build_conda.sh    
        
  MacOs38:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: compile-openvisus
      run: |
        export PYTHON_VERSION=3.8
        bash ./scripts/build_osx.sh
        cd build_osx/Release/OpenVisus  
        # ./scripts/build_conda.sh  BROKEN
        


  Linux36:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: compile-openvisus
      run: |
        docker run -d -it --name mydocker -v $(pwd):/root/OpenVisus -w /root/OpenVisus -e PYTHON_VERSION=3.6 visus/travis-image /bin/bash 
        docker exec mydocker /bin/bash -c "./scripts/build_linux.sh"
        docker exec mydocker /bin/bash -c "cd build_linux/Release/OpenVisus && bash ./scripts/build_conda.sh"      
        
  Linux37:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: compile-openvisus
      run: |
        docker run -d -it --name mydocker -v $(pwd):/root/OpenVisus -w /root/OpenVisus -e PYTHON_VERSION=3.7 visus/travis-image /bin/bash 
        docker exec mydocker /bin/bash -c "./scripts/build_linux.sh"
        docker exec mydocker /bin/bash -c "cd build_linux/Release/OpenVisus && bash ./scripts/build_conda.sh"   
        
  Linux38:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: compile-openvisus
      run: |
        docker run -d -it --name mydocker -v $(pwd):/root/OpenVisus -w /root/OpenVisus -e PYTHON_VERSION=3.8 visus/travis-image /bin/bash 
        docker exec mydocker /bin/bash -c "./scripts/build_linux.sh"
        # docker exec mydocker /bin/bash -c "cd build_linux/Release/OpenVisus && bash ./scripts/build_conda.sh"                   
