name: C/C++ CI

on: [push]

jobs:
  build-for-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: compile
      run: |
        sudo apt-get update
        sudo apt-get install -y wget bzip2 python3-pip libgsl-dev libboost-dev
        sudo python3 -m pip install -U pip setuptools

  build-for-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: compile
      run: brew update && brew upgrade && brew install boost gsl hdf5 cmake python

