name: C/C++ CI

on: [push]

jobs:
  build-for-linux:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: compile-openvisus
      run: |
        docker run -d -it --name mydocker -v $(pwd):/root/OpenVisus -w /root/OpenVisus -e GIT_TAG=${CIRCLE_TAG} -e PYTHON_VERSION=3.8 visus/travis-image /bin/bash 
        docker exec mydocker /bin/bash -c "./scripts/build_linux.sh"
        docker exec mydocker /bin/bash -c "cd build_linux/Release/OpenVisus"
        docker exec mydocker /bin/bash -c "bash .scripts/build_conda.sh"      
        
  build-for-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: compile-openvisus
      run: |
        export PYTHON_VERSION=3.6
        export GIT_TAG=${TRAVIS_TAG}
        bash ./scripts/build_osx.sh
        cd build_osx/Release/OpenVisus 
        if [[ "${PYTHON_VERSION}" != "3.8" ]] ; then bash ./scripts/build_conda.sh ; fi      

